config/routes.rb
Rails.application.routes.draw do

  get 'survey/landing'

  resources :blog_comment, only: [] do
    collection do
      get 'new', to: :new
    end
  end

  resources :blog, only: [:show,:index]
  resources :media_contents, only: [:create]

  scope 'admin' do
    resources :blog do
      collection do
        post 'new', to: :new
        post 'update', to: :update
      end
    end
  end

  root to: 'home_page#home'
  get 'ling/index', to: 'ling#ling_index'

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    #get  '/users' => 'home_page#home'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :payment,  only: [:new, :create, :show]

  namespace :api, defaults:{ format: :json }do
      namespace :v1 do
        resources :products, :only => [:show,:index]
        resources :category_has_products, :only => [:show,:index]
      end
    end

  #  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  #devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  scope "(:locale)",locale:/#{I18n.available_locales.join("|")}/ do

  #  devise_scope :user do
  #      delete '/users/sign_out' => 'devise/sessions#destroy'
  #  end


    resources :category, except:[:delete] do
      collection do
        get 'show', to: :show
      end
      resources :product, only:[]  do
        collection do
          get 'showall', to: :showall
          get 'newest', to: :newest
          get 'pricelow', to: :pricelow
          get 'pricehigh', to: :pricehigh
          post 'pricerange', to: :pricerange
        end
      end
      #resources :user do
      #  collection do
      #    get '/users/sign_out' => 'devise/sessions#destroy'
      #  end
      #end
    end

    resources :blog_comment, only: [] do
      collection do
        get 'new', to: :new
      end
    end

    resources :blog, only: [:show,:index]

    resources :product, only:[]  do
      member do
        get 'show', to: :show
      end
    end

    resources :review, only: [] do
      collection do
        get 'create', to: :create
      end
    end

    scope 'admin' do
      resources :product do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          post 'change', to: :change
          get 'list', to: :list
          get 'status', to: :status
          get 'showimage', to: :showimage
          post 'sortimages', to: :sortimages
        end
      end
    end

    scope 'admin' do
      resources :review do
        collection do
          get 'list', to: :list
          get 'see', to: :see
          get 'latest', to: :see
          get 'delete', to: :delete
        end
      end
    end

    scope 'admin' do
      resources :sale do
        collection do
          get 'listsales', to: :listsales
          get 'details', to: :details
          get 'listallsales', to: :listsales
          get 'listprocessingsales', to: :listprocessingsales
          get 'listcompletedsales', to: :listcompletedsales
          get 'listcanceledsales', to: :listcanceledsales
          get 'changeprocessing', to: :changeprocessing
          get 'changecompleted', to: :changecompleted
          get 'changecanceled', to: :changecanceled
        end
      end
    end

    #assert_generates '../category/status', controller: 'category', action: 'status'
    scope 'admin' do
      resources :category do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          get 'list', to: :list
          get 'status', to: :status
          post 'change', to: :change
        end
      end

      scope 'admin' do
        resources :blog do
          collection do
            get 'add', to: :add
            post 'new', to: :new
            post 'change', to: :change
          end
        end
      end

      resources :product_images do
         collection do
           post 'create', to: :create
           post 'createExisting', to: :createExisting
           post 'updateorder', to: :updateorder
         end
      end
    end

    post 'addtocart', to: 'application#addtocart'
    get 'addtocartget', to: 'application#addtocartget'
    get 'addtowishlist', to: 'application#addtowishlist'
    get 'refreshcart', to: 'shop#refreshcart'

    get 'wishlist', to: 'shop#wishlistshow'
    get 'deletewishlist', to: 'shop#deletewishlist'


    resources :checkout, only: [] do
      collection do
        get 'index', to: :index
        get 'first', to: :first
        post 'first_data', to: :first
        get 'billing', to: :billing
        post 'billingComplete', to: :billingComplete
        get 'second', to: :second
        get 'cart', to: :cart
        get 'deletecart', to: :deletecart
        post 'yesbillingaddress', to: :yesbillingaddress
        post 'yesdeliveryaddress', to: :yesdeliveryaddress
      end
    end

    resources :category, only: [] do
      resources :product, only: [] do
        collection do
          get 'showforcategory', to: :showforcategory
        end
      end
    end

    get 'home', to: 'home_page#home'
    get 'team', to: 'hometeam#index'
    get 'admin/index', to: 'admin#admin_index'
    get 'customer-survey', to: 'survey#landing'
    get 'great', to: 'survey#yes'
    get 'oh-no', to: 'survey#no'

    resources :admin do
      collection do
        get 'userlist', to: :user
        get 'beadmin', to: :beadmin
        get 'removeadmin', to: :removeadmin
      end
    end
    resources :product_images
  end
end

app/views/admin/_index.html.erb
<div id="page-wrapper" style="background-color: #FFFFFF;">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header" align="center" style="font-size: 3.5em; margin-top: 20px">Dashboard</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <!-- /.row -->
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-comments fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><%= Review.where("created_at > ?", 1.day.ago).size %></div>
                            <div>New Comments!</div>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-yellow">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-shopping-cart fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge"><%= @orderstransaction.size %></div>
                            <div>New Orders!</div>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
             <div class="panel panel-green">
                 <div class="panel-heading">
                     <div class="row">
                         <div class="col-xs-3">
                             <i class="fa fa-barcode fa-5x"></i>
                         </div>
                         <div class="col-xs-9 text-right">
                             <div class="huge"><%= Product.where("quantity > ?", 0).size %></div>
                             <div>Stock available!</div>
                         </div>
                     </div>
                 </div>
                 <a href="#">
                     <div class="panel-footer">
                         <span class="pull-left">View Details</span>
                         <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                         <div class="clearfix"></div>
                     </div>
                 </a>
             </div>
         </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-red">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-ticket fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">0</div>
                            <div>Support Tickets!</div>
                        </div>
                    </div>
                </div>
                <a href="#">
                    <div class="panel-footer">
                        <span class="pull-left">View Details</span>
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-8">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bar-chart-o fa-fw"></i> Sales chart
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div>
                      <%= area_chart Order.group_by_hour(:created_at, range: 8.hours.ago..Time.now).count %>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-usd fa-fw"></i> Latest sales
                    <div class="pull-right">
                        <div class="btn-group">
                            <%= link_to 'Latest sales', listsales_sale_index_path, remote: true %>
                        </div>
                    </div>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover table-striped">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Created at</th>
                                            <th>Braintree ID</th>
                                            <th>Amount</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <% @orderstransaction.each do |t| %>
                                        <tr>
                                            <td><%= t.order_id %></td>
                                            <td><%= time_ago_in_words( t.created_at ) + " ago" %></td>
                                            <td><%= t.braintreeid %></td>
                                            <td><%= t.amount %></td>
                                        </tr>
                                        <% end %>
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.col-lg-4 (nested) -->

                        <!-- /.col-lg-8 (nested) -->
                    </div>
                    <!-- /.row -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->

            <!-- /.panel -->
        </div>
        <!-- /.col-lg-8 -->
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-bell fa-fw"></i> Notifications Panel
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="list-group">
                        <a href="#" class="list-group-item">
                            <i class="fa fa-comment fa-fw"></i> New Comment
                            <span class="pull-right text-muted small"><em>4 minutes ago</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                            <span class="pull-right text-muted small"><em>12 minutes ago</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-envelope fa-fw"></i> Message Sent
                            <span class="pull-right text-muted small"><em>27 minutes ago</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-tasks fa-fw"></i> New Task
                            <span class="pull-right text-muted small"><em>43 minutes ago</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-upload fa-fw"></i> Server Rebooted
                            <span class="pull-right text-muted small"><em>11:32 AM</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-bolt fa-fw"></i> Server Crashed!
                            <span class="pull-right text-muted small"><em>11:13 AM</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-warning fa-fw"></i> Server Not Responding
                            <span class="pull-right text-muted small"><em>10:57 AM</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-shopping-cart fa-fw"></i> New Order Placed
                            <span class="pull-right text-muted small"><em>9:49 AM</em>
                            </span>
                        </a>
                        <a href="#" class="list-group-item">
                            <i class="fa fa-money fa-fw"></i> Payment Received
                            <span class="pull-right text-muted small"><em>Yesterday</em>
                            </span>
                        </a>
                    </div>
                    <!-- /.list-group -->
                    <a href="#" class="btn btn-default btn-block">View All Alerts</a>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->

            <!-- /.panel -->
            <!-- /.panel .chat-panel -->
        </div>
        <!-- /.col-lg-4 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->

app/views/admin/_userlist.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Users</h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Users</h3>
      </div>
      <div class="panel-body">
        <div class="tab-pane" id="tab-discount">
          <div class="table-responsive">
            <table id="discount" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <td class="text-left">Id</td>
                  <td class="text-left">Email</td>
                  <td class="text-left">Role</td>
                  <td class="text-left">Status</td>
                  <td class="text-left">Action</td>
                </tr>
              </thead>
              <tbody>
                <% @userslist.each do |t| %>
                <tr>
                  <td><%= t.id %></td>
                  <td><%= t.email %></td>
                  <td><%= t.role %></td>

                  <td> Active </td>
                  <td><!-- <a href="/category/edit/<%= t.id %>" data-toggle="tooltip" title="Edit" class="btn btn-default"><i class="fa fa-pencil"></i></a>-->
                  <%= link_to '', beadmin_admin_index_path( :id => t.id ), :class=>"btn btn-default fa fa-arrow-circle-up", remote: true %>
                  <%= link_to '', removeadmin_admin_index_path( :id => t.id ), :class=>"btn btn-default fa fa-arrow-circle-down", remote: true %>
                  <!--<%= link_to '', status_category_index_path( :id => t.id ), :class=>"btn btn-default fa fa-eye", remote: true %>-->
                  <!-- <a href="/category/status/<%= t.id %>" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></td>
                  <a href="/admin/index" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></div></td> -->
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/admin/admin_index.html.erb
<div id="indexcambio">

  <%= render 'admin/index' %>

</div>

app/views/admin/userlist.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( "userlist" ) ) %>" );