config/routes.rb
Rails.application.routes.draw do

  get 'survey/landing'

  resources :blog_comment, only: [] do
    collection do
      get 'new', to: :new
    end
  end

  resources :blog, only: [:show,:index]
  resources :media_contents, only: [:create]

  scope 'admin' do
    resources :blog do
      collection do
        post 'new', to: :new
        post 'update', to: :update
      end
    end
  end

  root to: 'home_page#home'
  get 'ling/index', to: 'ling#ling_index'

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    #get  '/users' => 'home_page#home'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :payment,  only: [:new, :create, :show]

  namespace :api, defaults:{ format: :json }do
      namespace :v1 do
        resources :products, :only => [:show,:index]
        resources :category_has_products, :only => [:show,:index]
      end
    end

  #  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  #devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  scope "(:locale)",locale:/#{I18n.available_locales.join("|")}/ do

  #  devise_scope :user do
  #      delete '/users/sign_out' => 'devise/sessions#destroy'
  #  end


    resources :category, except:[:delete] do
      collection do
        get 'show', to: :show
      end
      resources :product, only:[]  do
        collection do
          get 'showall', to: :showall
          get 'newest', to: :newest
          get 'pricelow', to: :pricelow
          get 'pricehigh', to: :pricehigh
          post 'pricerange', to: :pricerange
        end
      end
      #resources :user do
      #  collection do
      #    get '/users/sign_out' => 'devise/sessions#destroy'
      #  end
      #end
    end

    resources :blog_comment, only: [] do
      collection do
        get 'new', to: :new
      end
    end

    resources :blog, only: [:show,:index]

    resources :product, only:[]  do
      member do
        get 'show', to: :show
      end
    end

    resources :review, only: [] do
      collection do
        get 'create', to: :create
      end
    end

    scope 'admin' do
      resources :product do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          post 'change', to: :change
          get 'list', to: :list
          get 'status', to: :status
          get 'showimage', to: :showimage
          post 'sortimages', to: :sortimages
        end
      end
    end

    scope 'admin' do
      resources :review do
        collection do
          get 'list', to: :list
          get 'see', to: :see
          get 'latest', to: :see
          get 'delete', to: :delete
        end
      end
    end

    scope 'admin' do
      resources :sale do
        collection do
          get 'listsales', to: :listsales
          get 'details', to: :details
          get 'listallsales', to: :listsales
          get 'listprocessingsales', to: :listprocessingsales
          get 'listcompletedsales', to: :listcompletedsales
          get 'listcanceledsales', to: :listcanceledsales
          get 'changeprocessing', to: :changeprocessing
          get 'changecompleted', to: :changecompleted
          get 'changecanceled', to: :changecanceled
        end
      end
    end

    #assert_generates '../category/status', controller: 'category', action: 'status'
    scope 'admin' do
      resources :category do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          get 'list', to: :list
          get 'status', to: :status
          post 'change', to: :change
        end
      end

      scope 'admin' do
        resources :blog do
          collection do
            get 'add', to: :add
            post 'new', to: :new
            post 'change', to: :change
          end
        end
      end

      resources :product_images do
         collection do
           post 'create', to: :create
           post 'createExisting', to: :createExisting
           post 'updateorder', to: :updateorder
         end
      end
    end

    post 'addtocart', to: 'application#addtocart'
    get 'addtocartget', to: 'application#addtocartget'
    get 'addtowishlist', to: 'application#addtowishlist'
    get 'refreshcart', to: 'shop#refreshcart'

    get 'wishlist', to: 'shop#wishlistshow'
    get 'deletewishlist', to: 'shop#deletewishlist'


    resources :checkout, only: [] do
      collection do
        get 'index', to: :index
        get 'first', to: :first
        post 'first_data', to: :first
        get 'billing', to: :billing
        post 'billingComplete', to: :billingComplete
        get 'second', to: :second
        get 'cart', to: :cart
        get 'deletecart', to: :deletecart
        post 'yesbillingaddress', to: :yesbillingaddress
        post 'yesdeliveryaddress', to: :yesdeliveryaddress
      end
    end

    resources :category, only: [] do
      resources :product, only: [] do
        collection do
          get 'showforcategory', to: :showforcategory
        end
      end
    end

    get 'home', to: 'home_page#home'
    get 'team', to: 'hometeam#index'
    get 'admin/index', to: 'admin#admin_index'
    get 'customer-survey', to: 'survey#landing'
    get 'great', to: 'survey#yes'
    get 'oh-no', to: 'survey#no'

    resources :admin do
      collection do
        get 'userlist', to: :user
        get 'beadmin', to: :beadmin
        get 'removeadmin', to: :removeadmin
      end
    end
    resources :product_images
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController

  #before_action :require_admin, only: [:admin_index]
  respond_to :js
  def refreshcart
    current_cart
    @productcart = []
    session[:cart].each do |key, array|
      e = Product.find( key.to_s )
      e.quantity = array
      @productcart << e
    end
    print session[:cart]
    @productcart.each do |q|
      puts q.name
    end
  end

  def wishlistshow
    current_wishlist
    @wlshow = []
    session[:wishlist].each do |key, array|
      @wlshow << Product.find(key.to_s)
    end
    @wlshow = @wlshow.paginate(:page => params[:page],:per_page => 6)
  end
  def deletewishlist
    id = params[:id]
    current_wishlist
    @wlshow = []
    session[:wishlist].delete( id )
    session[:wishlist].each do |key, array|
      @wlshow << Product.find( key.to_s )
    end
    @wlshow = @wlshow.paginate(:page => params[:page],:per_page => 6)
    respond_to do |format|
        format.js
    end
  end

  # def deletecart
  #   id = params[:id]
  #   current_cart
  #   @productcart = []
  #   session[:cart].delete( id )
  #   session[:cart].each do |key, array|
  #     e = Product.find( key.to_s )
  #     e.quantity = array
  #     @productcart << e
  #   end
  #   @productcart.each do |q|
  #     print q.name
  #   end
  #   respond_to do |format|
  #     format.js
  #   end
  # end

end

app/views/shop/_deletecart.html.erb
<li class="pull-right"><button id="refresh" class="btn btn-template-main"><i class="fa fa-refresh fa-lg"></i>Update</button></button></li>
<br><br>
  <% @productcart.each do |a| %>
    <li>
        <pre><strong><%= a.name %>: $<%= a.price %> </strong></pre>
        <button data-toggle="tooltip" title="Delete" id="delete" name=<%= a.id %> class="btn btn-primary"><i class="fa fa-trash"></i></button>
        <%= link_to '', deletecart_path( :id => a.id ), :class=>"btn btn-default fa fa-pencil", remote: true %>
    </li>
  <% end %>
    <li>
        <a class="text-center" href="#">
            <button type="submit" class="btn btn-template-main" disabled><i class="fa fa-shopping-cart"></i>Go to cart</button>
        </a>
    </li>

app/views/shop/_refreshcart.html.erb
<li class="text-center"><button id="refresh" class="btn btn-template-main"><i class="fa fa-refresh fa-lg"></i>Update</button></button></li>
<br>
<div>
	<table id="discount" class="table table-striped table-bordered table-hover">
		<thead>
			<tr>
				<td class="text-left">Name</td>
				<td class="text-left">Price</td>
			</tr>
		</thead>
		<tbody>
			<% @productcart.each do |a| %>
			<tr>
				<td><%= a.name %></td>
				<td><%= a.price %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<li class="text-center"><a class="text-center" href="<%= cart_checkout_index_path %>"><button href="<%= cart_checkout_index_path %>" class="btn btn-template-main" disabled><i class="fa fa-shopping-cart"></i>Go to cart</button></a></li>

app/views/shop/_showWL.html.erb
<div id="addedsuccess"></div>
<div class="row products">
	<% @wlshow.each do |c| %>
	<div class="col-md-3 col-sm-5">
		<div class="product">
			<div>
				<div class="box-image custom-box-image">
					<div class="image" id= "pimageWL">
						<a href="<%=product_path( c.id ) %>">
							<%product_image = ProductImage.find_by(product_id: c.id.to_s )%>
							<%if product_image.nil?%>
							<%= image_tag("shop/no-preview.jpg", class: "img-responsive image1") %>
							<%else%>
							<img src="<%=product_image.image.url%>" class="img-responsive">
							<%end%>
						</a>
					</div>
					<div class="text custom-text-add-to-cart">
						<a href="<%= addtocartget_path( :id => c.id ) %>" data-remote="true" class="btn btn-template-main" id="btnaddtocart"><i class="fa fa-shopping-cart"></i>Add to cart</button></a>
						<a href="<%= deletewishlist_path( :id => c.id ) %>" data-remote="true" class="btn btn-danger" id="deletewishlist"><i class="fa fa-times"></i></a>
					</div>
				</div>
				<% if c.discount != 0.0%>
				<div class="ribbon sale">
					<div class="theribbon">SALE</div>
					<div class="ribbon-background"></div>
				</div>
				<%end%>
				<% if c.created_at > 10.days.ago %>
				<div class="ribbon new">
					<div class="theribbon">NEW</div>
					<div class="ribbon-background"></div>
				</div>
				<% end %>
			</div>
			<div class="text">
				<h3><%=c.name%></h3>
				<% if c.discount != 0.0%>
				<p class="price"><del>$<%= c.price %></del> $<%= (c.price.to_d - c.discount.to_i) %></p>
				<%else%>
				<p class="price">$<%=c.price%></p>
				<%end%>
			</div>
		</div>
	</div>
	<%end%>
</div>
<div class="col-sm-12">
	<div class="center">
		<%= will_paginate @wlshow, renderer: BootstrapPagination::Rails, inner_window: 1, outer_window: 1,previous_label: "«" , next_label: "»"%>
	</div>
</div>

app/views/shop/deletecart.js.erb
$( "#refresh" ).html( "<%= escape_javascript( render( "deletecart" ) ) %>" );

app/views/shop/deletewishlist.js.erb
$( "#container-wishlist" ).html( "<%= escape_javascript( render( "showWL" ) ) %>" );
$( "#numberW" ).html( "<%= session[:wishlist].count %>" );

app/views/shop/refreshcart.js.erb
$( "#refresh" ).html( "<%= escape_javascript( render( "refreshcart" ) ) %>" );

app/views/shop/wishlistshow.html.erb
<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <h1>Wish List </h1>
            </div>
            <div class="col-md-5">
                <ul class="breadcrumb">
                    <li><%= link_to "HOME", root_path%>
                    </li>
                    <li>Wish List </li>
                </ul>

            </div>
        </div>
    </div>
</div>
<div id="content">
  <div class="container" id="container-wishlist">
    <%= render 'shop/showWL' %>
  </div>
    <!-- /.container -->
</div>

app/views/shop/wishlistshow.js.erb
$( "#container-wishlist" ).html( "<%= escape_javascript( render( "showWL" ) ) %>" );