config/routes.rb
Rails.application.routes.draw do

  get 'survey/landing'

  resources :blog_comment, only: [] do
    collection do
      get 'new', to: :new
    end
  end

  resources :blog, only: [:show,:index]
  resources :media_contents, only: [:create]

  scope 'admin' do
    resources :blog do
      collection do
        post 'new', to: :new
        post 'update', to: :update
      end
    end
  end

  root to: 'home_page#home'
  get 'ling/index', to: 'ling#ling_index'

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    #get  '/users' => 'home_page#home'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :payment,  only: [:new, :create, :show]

  namespace :api, defaults:{ format: :json }do
      namespace :v1 do
        resources :products, :only => [:show,:index]
        resources :category_has_products, :only => [:show,:index]
      end
    end

  #  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  #devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  scope "(:locale)",locale:/#{I18n.available_locales.join("|")}/ do

  #  devise_scope :user do
  #      delete '/users/sign_out' => 'devise/sessions#destroy'
  #  end


    resources :category, except:[:delete] do
      collection do
        get 'show', to: :show
      end
      resources :product, only:[]  do
        collection do
          get 'showall', to: :showall
          get 'newest', to: :newest
          get 'pricelow', to: :pricelow
          get 'pricehigh', to: :pricehigh
          post 'pricerange', to: :pricerange
        end
      end
      #resources :user do
      #  collection do
      #    get '/users/sign_out' => 'devise/sessions#destroy'
      #  end
      #end
    end

    resources :blog_comment, only: [] do
      collection do
        get 'new', to: :new
      end
    end

    resources :blog, only: [:show,:index]

    resources :product, only:[]  do
      member do
        get 'show', to: :show
      end
    end

    resources :review, only: [] do
      collection do
        get 'create', to: :create
      end
    end

    scope 'admin' do
      resources :product do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          post 'change', to: :change
          get 'list', to: :list
          get 'status', to: :status
          get 'showimage', to: :showimage
          post 'sortimages', to: :sortimages
        end
      end
    end

    scope 'admin' do
      resources :review do
        collection do
          get 'list', to: :list
          get 'see', to: :see
          get 'latest', to: :see
          get 'delete', to: :delete
        end
      end
    end

    scope 'admin' do
      resources :sale do
        collection do
          get 'listsales', to: :listsales
          get 'details', to: :details
          get 'listallsales', to: :listsales
          get 'listprocessingsales', to: :listprocessingsales
          get 'listcompletedsales', to: :listcompletedsales
          get 'listcanceledsales', to: :listcanceledsales
          get 'changeprocessing', to: :changeprocessing
          get 'changecompleted', to: :changecompleted
          get 'changecanceled', to: :changecanceled
        end
      end
    end

    #assert_generates '../category/status', controller: 'category', action: 'status'
    scope 'admin' do
      resources :category do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          get 'list', to: :list
          get 'status', to: :status
          post 'change', to: :change
        end
      end

      scope 'admin' do
        resources :blog do
          collection do
            get 'add', to: :add
            post 'new', to: :new
            post 'change', to: :change
          end
        end
      end

      resources :product_images do
         collection do
           post 'create', to: :create
           post 'createExisting', to: :createExisting
           post 'updateorder', to: :updateorder
         end
      end
    end

    post 'addtocart', to: 'application#addtocart'
    get 'addtocartget', to: 'application#addtocartget'
    get 'addtowishlist', to: 'application#addtowishlist'
    get 'refreshcart', to: 'shop#refreshcart'

    get 'wishlist', to: 'shop#wishlistshow'
    get 'deletewishlist', to: 'shop#deletewishlist'


    resources :checkout, only: [] do
      collection do
        get 'index', to: :index
        get 'first', to: :first
        post 'first_data', to: :first
        get 'billing', to: :billing
        post 'billingComplete', to: :billingComplete
        get 'second', to: :second
        get 'cart', to: :cart
        get 'deletecart', to: :deletecart
        post 'yesbillingaddress', to: :yesbillingaddress
        post 'yesdeliveryaddress', to: :yesdeliveryaddress
      end
    end

    resources :category, only: [] do
      resources :product, only: [] do
        collection do
          get 'showforcategory', to: :showforcategory
        end
      end
    end

    get 'home', to: 'home_page#home'
    get 'team', to: 'hometeam#index'
    get 'admin/index', to: 'admin#admin_index'
    get 'customer-survey', to: 'survey#landing'
    get 'great', to: 'survey#yes'
    get 'oh-no', to: 'survey#no'

    resources :admin do
      collection do
        get 'userlist', to: :user
        get 'beadmin', to: :beadmin
        get 'removeadmin', to: :removeadmin
      end
    end
    resources :product_images
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  #before_action :authenticate_user!
  #before_action :require_admin

  def add
    respond_to do |format|
    	format.js
    end
  end

  def new
    t = Article.new
    t.title = params['title']
    t.description = params['description']
    t.content = params['content']
    t.save!
    session[:articleid] = t.id
  end

  def index
    @name_blog = "Bags blog"
    @articles = Article.all.reverse_order
    @image = Media.all
  end

  def show
    @article = Article.find_by( id: params[:id] )
    @comments = BlogComment.where(article_id: params[:id]).order('created_at DESC')

  end

  def update

  end

  def change

  end


end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_addblog.html.erb
<%= tinymce_assets %>
<div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">
      <button data-toggle="tooltip" title="Save" id="addblog" class="btn btn-primary"><i class="fa fa-save"></i></button>
      <!--<button title="Saveimage" id="saveimage" class="btn btn-primary hidden"><i class="fa fa-save"></i></button>-->
      <a href="/admin/index" id="finishadd" title="Finish" class="btn btn-primary hidden"><i class="fa fa-check"></i></a>
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Blog</h1>
    </div>



    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Add a new post</h3>
      </div>
      <div class="panel-body" style="margin-top: 20px">
        <form action="/blog/new" method="post" enctype="multipart/form-data" id="form-blog" class="form-horizontal">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <ul class="nav nav-tabs">
            <li class="active" id="general"><a href="#tab-data" data-toggle="tab">General</a></li>
          </ul>

          <div class="tab-content" style="margin-top: 15px">
            <div class="tab-pane active" id="tab-data">
              <div class="form-group required">
                <label class="col-sm-2 control-label" for="input-title">Author</label>
                <div class="col-sm-10">
                  <input type="text" name="blog_author" value="" placeholder="Post author" id="name" class="form-control">
                </div>
              </div>
              <div class="form-group required">
                <label class="col-sm-2 control-label" for="input-title">Title</label>
                <div class="col-sm-10">
                  <input type="text" name="blog_tittle" value="" placeholder="Post title" id="title" class="form-control">
                </div>
              </div>
              <div class="form-group required">
                <label class="col-sm-2 control-label" for="input-description1">Short description</label>
                <div class="col-sm-10">
                  <textarea name="blog_description1" placeholder="Description" style="min-width: 100%" style="max-width: 100%"  id="description"></textarea>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label" for="input-content">Content</label>
                <div class="col-sm-10">
                   <textarea name="content" rows="15" id="content" class="form-control"></textarea>
                </div>
              </div>

            </div>
          </div>
            </form>
          </div>
        </div>
    </div>

app/views/blog/_addblog2.html.erb
<%= stylesheet_link_tag 'blog', media: 'all' %>

<div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">
  <div class="pull-right">
    <button data-toggle="tooltip" title="Save" id="saveContent" class="btn btn-primary"><i class="fa fa-save"></i></button>
    <%= link_to('<button title="Save" id="addblog" class="btn btn-primary"><i class="fa fa-check"></i></button>'.html_safe, admin_index_path, id:"finish",class:"hidden") %>
  </div>
  <h1>Blog</h1>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><i class="fa fa-pencil"></i>Post new article</h3>
  </div>
  <ul class="nav nav-tabs" style="margin: 1em;">
    <li class="active" id="general"><a href="#tab-data" data-toggle="tab">General</a></li>
    <li id="idImage" class="active hidden"><a href="#tab-image" data-toggle="tab">Image</a></li>
  </ul>
  <div class="panel-body" id="tab-data" style="margin-top: 20px">
      <%= form_tag('admin/blog/new', id: 'form-blog', class: 'form-horizontal') do %>
      <div id="tab-data">
        <div class="form-group required">
          <label class="col-sm-1 control-label">Title</label>
          <div class="col-sm-11 ">
            <input type="text" placeholder="Article Title" class="form-control" id="title" style="text-align:center; font-weight: bold;"/>
          </div>
        </div>
        <div class="form-group required">
          <label class="col-sm-1 control-label">Summary</label>
          <div class="col-sm-11">
            <textarea class="form-control" placeholder="Put here a brief description about article" style="min-width: 100%; max-width: 100%; min-height: 35px;" id="description"></textarea>
          </div>
        </div>
        <div class="form-group required">
          <label class="col-sm-1 control-label">Content</label>
          <div class="col-sm-11">
            <div id="editor">
              <div id='edit' style="margin-top: 30px;">
              </div>
            </div>
          </div>
        </div>
        <br>
      </div>
    <%  end %>
  </div>
  <div class="panel-body hidden" id="tab-image">
    <form action="/media_contents" id="media-dropzone" class="dropzone" enctype="multipart/form-data">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
      <div class="fallback">
        <input name="media" type="file" multiple />
      </div>
    </form>
  </div>
</div>
<%= javascript_include_tag 'blog' %>

app/views/blog/_content.html.erb
<div class="container">
                <div class="row">
                  <div class="col-md-9" id="blog-listing-medium">
                    <% @articles.each do |article|%>
                    <section class="post">
                      <div class="row">
                        <div class="col-md-4">
                          <div class="image" style="height: 197px;">
                              <% image = @image.find_by article_id: article.id %>
                              <%= link_to( image_tag( image.file_name.url , class:"img-responsive", alt:"Example blog post alt" ), blog_path(article.id) )%>
                          </div>
                        </div>
                        <div class="col-md-8">
                          <h2><%= link_to article.title, blog_path(article.id) %></h2>
                          <div class="clearfix">
                            <p class="author-category">By Diana Miller </a> in <a href="#">Wayuu Mochila Bags' Company Info Leave a comment</a>
                            </p>
                            <p class="date-comments">
                              <a href="#"><i class="fa fa-calendar-o"></i><% t=article.created_at %><%= t.strftime("%b %d, %Y") %></a>
                              <a href="#"><i class="fa fa-comment-o"></i> Comments</a>
                            </p>
                          </div>
                          <p class="intro"><%= article.description %></p>
                          <p class="read-more"><%= link_to "Continue reading", blog_path(article.id),class:"btn btn-template-main" %></p>
                        </div>
                      </div>
                    </section>
                    <% end %>
                  </div>
                </div>
            </div>

app/views/blog/_post.html.erb
<div class="container">

  <div class="row">

    <div class="col-md-9" id="blog-post">
      <p class="text-muted text-uppercase mb-small text-right">Posted on <%= @article.created_at.strftime("%b %d, %Y") %>
        by Diana Miller
      </p>

      <br>
      <p class="lead" align="justify"><%= @article.description %></p>

      <div>
        <%=  @article.content.html_safe %>
      </div>
    </div>
  </div>

      <!---  REVIEWS  ----------->
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><i class="fa fa-pencil"></i>Reviews</h3>
        </div>
        <div class="panel-body" style="margin-top: 20px">
          <form action="<%= blog_comment_index_path %>" method="get" id="form-comment" class="form-horizontal">
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= hidden_field_tag :article, @article.id %>
            <ul class="nav nav-tabs">
              <li class="active" id="general"><a href="#tab-data" data-toggle="tab">Reviews</a></li>
              <li id="create"><a href="#tab-create" data-toggle="tab">Write reviews</a></li>
            </ul>

            <div class="tab-content" style="margin-top: 15px">
              <div class="tab-pane active" id="tab-data">
                <div class="well">
                  <% @comments.each do |t| %>
                    <div class="row">
                      <div class="col-md-12">
                        <p><%= t.name %></p>
                        <span class="pull-right"><%= time_ago_in_words( t.created_at ) + " ago" %></span>
                        <p><%= t.comment %></p>
                      </div>
                    </div>
                    <hr>
                  <% end %>
                </div>
              </div>

              <div class="tab-pane" id="tab-create">
                <div class="form-group">
                  <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-name">Name</label>
                    <div class="col-sm-10">
                      <input type="text" name="name" value="" placeholder="Name" id="name" class="form-control" />
                    </div>
                    <br><br>
                    <label class="col-sm-2 control-label" for="input-name">Email</label>
                    <div class="col-sm-10">
                      <input type="text" name="email" value="" placeholder="Email" id="email" class="form-control" />
                    </div>
                  </div>
                  <div class="form-group">
                    <label class="col-sm-2 control-label" for="input-description1">Description</label>
                    <div class="col-sm-10">
                      <textarea class="form-control" type="text" name="comment" placeholder="Description" style="min-width: 100%; max-width: 100%;
                       min-height: 45px;"id="description"></textarea>
                    </div>
                  </div>

                  <div class="col-sm-12" align="right">
                    <button data-toggle="tooltip" title="Save" form="form-comment" id="addComment" class="btn btn-primary" style="width: 150px; height: 50px;">Send</button>
                  </div>

                </div>
              </div>
            </div>
          </form>
        </div>
      </div>

      <div class="box social" id="product-social">
          <h4>Show it to your friends</h4>
          <p>
              <a href="#" class="external facebook" data-animate-hover="pulse"><i class="fa fa-facebook"></i></a>
              <a href="#" class="external gplus" data-animate-hover="pulse"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="external twitter" data-animate-hover="pulse"><i class="fa fa-twitter"></i></a>
              <a href="#" class="email" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
          </p>
      </div>
      <br>

    </div>
  </div>
</div>

app/views/blog/add.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( 'addblog2' ) ) %>" );

app/views/blog/index.html.erb
<div id="heading-breadcrumbs">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h1><%= @name_blog %></h1>
                    </div>
                    <div class="col-md-6">
                        <ul class="breadcrumb">
                            <li><%=link_to "Home", root_path %>
                            </li>
                            <li>Blog</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="content">
          <%= render partial:'blog/content' %>
        </div>

app/views/blog/show.html.erb
<div id="heading-breadcrumbs">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <h1><%= @article.title %></h1>
                    </div>
                    <div class="col-md-6">
                        <ul class="breadcrumb">
                            <li><%=link_to "Home", root_path %>
                            </li>
                            <li>Blog</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="content">
          <%= render partial:'blog/post' %>
        </div>