config/routes.rb
Rails.application.routes.draw do

  get 'survey/landing'

  resources :blog_comment, only: [] do
    collection do
      get 'new', to: :new
    end
  end

  resources :blog, only: [:show,:index]
  resources :media_contents, only: [:create]

  scope 'admin' do
    resources :blog do
      collection do
        post 'new', to: :new
        post 'update', to: :update
      end
    end
  end

  root to: 'home_page#home'
  get 'ling/index', to: 'ling#ling_index'

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_scope :user do
    #get  '/users' => 'home_page#home'
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :payment,  only: [:new, :create, :show]

  namespace :api, defaults:{ format: :json }do
      namespace :v1 do
        resources :products, :only => [:show,:index]
        resources :category_has_products, :only => [:show,:index]
      end
    end

  #  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], as: :finish_signup

  #devise_for :users, skip: [:session, :password, :registration, :confirmation], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  scope "(:locale)",locale:/#{I18n.available_locales.join("|")}/ do

  #  devise_scope :user do
  #      delete '/users/sign_out' => 'devise/sessions#destroy'
  #  end


    resources :category, except:[:delete] do
      collection do
        get 'show', to: :show
      end
      resources :product, only:[]  do
        collection do
          get 'showall', to: :showall
          get 'newest', to: :newest
          get 'pricelow', to: :pricelow
          get 'pricehigh', to: :pricehigh
          post 'pricerange', to: :pricerange
        end
      end
      #resources :user do
      #  collection do
      #    get '/users/sign_out' => 'devise/sessions#destroy'
      #  end
      #end
    end

    resources :blog_comment, only: [] do
      collection do
        get 'new', to: :new
      end
    end

    resources :blog, only: [:show,:index]

    resources :product, only:[]  do
      member do
        get 'show', to: :show
      end
    end

    resources :review, only: [] do
      collection do
        get 'create', to: :create
      end
    end

    scope 'admin' do
      resources :product do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          post 'change', to: :change
          get 'list', to: :list
          get 'status', to: :status
          get 'showimage', to: :showimage
          post 'sortimages', to: :sortimages
        end
      end
    end

    scope 'admin' do
      resources :review do
        collection do
          get 'list', to: :list
          get 'see', to: :see
          get 'latest', to: :see
          get 'delete', to: :delete
        end
      end
    end

    scope 'admin' do
      resources :sale do
        collection do
          get 'listsales', to: :listsales
          get 'details', to: :details
          get 'listallsales', to: :listsales
          get 'listprocessingsales', to: :listprocessingsales
          get 'listcompletedsales', to: :listcompletedsales
          get 'listcanceledsales', to: :listcanceledsales
          get 'changeprocessing', to: :changeprocessing
          get 'changecompleted', to: :changecompleted
          get 'changecanceled', to: :changecanceled
        end
      end
    end

    #assert_generates '../category/status', controller: 'category', action: 'status'
    scope 'admin' do
      resources :category do
        collection do
          get 'add', to: :add
          post 'new', to: :new
          post 'update', to: :update
          get 'list', to: :list
          get 'status', to: :status
          post 'change', to: :change
        end
      end

      scope 'admin' do
        resources :blog do
          collection do
            get 'add', to: :add
            post 'new', to: :new
            post 'change', to: :change
          end
        end
      end

      resources :product_images do
         collection do
           post 'create', to: :create
           post 'createExisting', to: :createExisting
           post 'updateorder', to: :updateorder
         end
      end
    end

    post 'addtocart', to: 'application#addtocart'
    get 'addtocartget', to: 'application#addtocartget'
    get 'addtowishlist', to: 'application#addtowishlist'
    get 'refreshcart', to: 'shop#refreshcart'

    get 'wishlist', to: 'shop#wishlistshow'
    get 'deletewishlist', to: 'shop#deletewishlist'


    resources :checkout, only: [] do
      collection do
        get 'index', to: :index
        get 'first', to: :first
        post 'first_data', to: :first
        get 'billing', to: :billing
        post 'billingComplete', to: :billingComplete
        get 'second', to: :second
        get 'cart', to: :cart
        get 'deletecart', to: :deletecart
        post 'yesbillingaddress', to: :yesbillingaddress
        post 'yesdeliveryaddress', to: :yesdeliveryaddress
      end
    end

    resources :category, only: [] do
      resources :product, only: [] do
        collection do
          get 'showforcategory', to: :showforcategory
        end
      end
    end

    get 'home', to: 'home_page#home'
    get 'team', to: 'hometeam#index'
    get 'admin/index', to: 'admin#admin_index'
    get 'customer-survey', to: 'survey#landing'
    get 'great', to: 'survey#yes'
    get 'oh-no', to: 'survey#no'

    resources :admin do
      collection do
        get 'userlist', to: :user
        get 'beadmin', to: :beadmin
        get 'removeadmin', to: :removeadmin
      end
    end
    resources :product_images
  end
end

app/controllers/sale_controller.rb
class SaleController < ApplicationController

	respond_to :html, :js



	def listallsales

		@orderstransaction = CustomerTransaction.all.order("created_at DESC")

	end

	def listprocessingsales

		@orders = Order.where(order_status_id: 2).order("created_at DESC")
		@orderstransaction = []
		@orders.each do |t|
			@orderstransaction << CustomerTransaction.find_by(order_id: t.id)
		end

	end

	def listcompletedsales

		@orders = Order.where(order_status_id: 1).order("created_at DESC")
		@orderstransaction = []
		@orders.each do |t|
			@orderstransaction << CustomerTransaction.find_by(order_id: t.id)
		end

	end

	def listcanceledsales

		@orders = Order.where(order_status_id: 3).order("created_at DESC")
		@orderstransaction = []
		@orders.each do |t|
			@orderstransaction << CustomerTransaction.find_by(order_id: t.id)
		end

	end

	def listsales
		@orders = Order.where(order_status_id: 4).order("created_at DESC")
    @orderstransaction = []
    @orders.each do |t|
      @orderstransaction << CustomerTransaction.find_by(order_id: t.id)
    end
	end

	def details
		details = params[:id]
		@detailorder = Order.find( details )
		@deliverycustomer = Customer.find( @detailorder.customer_id )
		@deliveryaddress = Address.find( @detailorder.address_id )

		@transaction = CustomerTransaction.where("order_id = ?", @detailorder.id ).first
		puts @transaction.inspect
		@billingcustomer = Customer.find( @transaction.customer_id )
		puts "pailas"
		@billingaddress = Address.find( @transaction.address_id )


		@productsorder = OrderProduct.where("order_id = ?", @detailorder.id )

	end

	def changecompleted
		id = params["id"]
		order = Order.find( id )
		order.order_status_id = 1
		order.save

		redirect_to listcompletedsales_sale_index_path
	end

	def changeprocessing
		id = params["id"]
		order = Order.find( id )
		order.order_status_id = 2
		order.save

		redirect_to listprocessingsales_sale_index_path
	end

	def changecanceled
		id = params["id"]
		order = Order.find( id )
		order.order_status_id = 3
		order.save

		redirect_to listcanceledsales_sale_index_path
	end



end

app/views/sale/_details.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">

      <button title="Saveimage" id="saveimage" class="btn btn-primary hidden"><i class="fa fa-save"></i></button>
      <a href="/admin/index" id="finishadd" title="Finish" class="btn btn-primary hidden"><i class="fa fa-check"></i></a>
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Order <%= @detailorder.id %></h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Check order</h3>
      </div>
      <div class="panel-body" style="margin-top: 20px">
        <form action="/product/new" method="post" enctype="multipart/form-data" id="form-product" class="form-horizontal">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <ul class="nav nav-tabs">
            <li class="active" id="general"><a href="#tab-data" data-toggle="tab">General</a></li>
            <li id="delivery"><a href="#tab-delivery" data-toggle="tab">Delivery address</a></li>
            <li id="billing"><a href="#tab-billing" data-toggle="tab">Billing</a></li>
          </ul>

          <div class="tab-content" style="margin-top: 15px">
            <div class="tab-pane active" id="tab-data">
              <div class="form-group required">
                <div align="center">
                  <label for="input-name">Products</label>
                </div>
                <div class="col-sm-12">
                  <div class="table-responsive">
                    <table id="discount" class="table table-striped table-bordered table-hover">
                      <thead>
                        <tr>

                          <td class="text-left">Name</td>
                          <td class="text-left">Quantity</td>
                          <td class="text-left">Price</td>

                        </tr>
                      </thead>
                      <tbody>
                          <% @productsorder.each do |x| %>
                        <tr>
                              <td><%= x.name %></td>
                              <td><%= x.quantity %></td>
                              <td>$<%= x.price %></td>

                        <% end %>
                      </tbody>
                    </table>
                  </div>

                </div>
              </div>
              <div class="col-sm-4" align="center">
                <%= link_to ' Processing', changeprocessing_sale_index_path( :id => @detailorder.id ), :class=>"btn btn-primary fa fa-check", remote: true %>
              </div>
              <div class="col-sm-4" align="center">
                <%= link_to ' Complete', changecompleted_sale_index_path( :id => @detailorder.id ), :class=>"btn btn-success fa fa-check-square", remote: true %>
              </div>
              <div class="col-sm-4" align="center">
                <%= link_to ' Cancel', changecanceled_sale_index_path( :id => @detailorder.id ), :class=>"btn btn-danger fa fa-times", remote: true %>
              </div>
            </div>
            <div class="tab-pane" id="tab-delivery">
              <div class="form-group">

                <div class="col-sm-12">

                  <div class="span8">
                      <h3>Delivery information</h3>

                      <div class="col-sm-2" align="right">
                      <label class="control-label">Firstname:</label>
                      </div>
                      <div class="col-sm-10">
                          <p  class="form-control"><%= @deliverycustomer.firstname %></p>
                          <p class="help-block"></p>
                      </div>

                      <div class="col-sm-2" align="right">
                      <label class="control-label">Lastname:</label>
                      </div>
                      <div class="col-sm-10">
                          <p  class="form-control"><%= @deliverycustomer.lastname %></p>
                          <p class="help-block"></p>
                      </div>

                      <div class="col-sm-2" align="right">
                      <label class="control-label">Email:</label>
                      </div>
                      <div class="col-sm-10">
                          <p  class="form-control"><%= @deliverycustomer.email %></p>
                          <p class="help-block"></p>
                      </div>

                      <div class="col-sm-2" align="right">
                      <label class="control-label">Telephone:</label>
                      </div>
                      <div class="col-sm-10">
                          <p  class="form-control"><%= @deliverycustomer.telephone %></p>
                          <p class="help-block"></p>
                      </div>


                      <h3>Address</h3>
                      <div class="col-sm-2" align="right">
                      <label class="control-label">Street:</label>
                      </div>
                      <div class="col-sm-10">
                          <p  class="form-control"><%= @deliveryaddress.address %></p>
                          <p class="help-block"></p>
                      </div>

                      <div class="col-sm-2" align="right">
                      <label class="control-label">Country:</label>
                      </div>
                      <div class="col-sm-10">
                          <p  class="form-control"><%= Country.find( @deliveryaddress.country_id ).name %></p>
                          <p class="help-block"></p>
                      </div>

                      <div class="col-sm-2" align="right">
                      <label class="control-label">City:</label>
                      </div>
                      <div class="col-sm-10">
                          <p  class="form-control"><%= @deliveryaddress.city %></p>
                          <p class="help-block"></p>
                      </div>

                      <div class="col-sm-2" align="right">
                      <label class="control-label">State:</label>
                      </div>
                      <div class="col-sm-10">
                          <p  class="form-control"><%= @deliveryaddress.state %></p>
                          <p class="help-block"></p>
                      </div>

                      <div class="col-sm-2" align="right">
                      <label class="control-label">Zip:</label>
                      </div>
                      <div class="col-sm-10">
                          <p  class="form-control"><%= @deliveryaddress.zip %></p>
                          <p class="help-block"></p>
                      </div>



                  </div>

                </div>

              </div>
            </div>
            <div class="tab-pane" id="tab-billing">
              <div class="form-group">


                  <div class="col-sm-12">

                    <div class="span8">
                        <h3>Billing information</h3>
                        <div class="col-sm-2" align="right">
                        <label class="control-label">Braintree ID:</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= @transaction.braintreeid %></p>
                            <p class="help-block"></p>
                        </div>

                        <div class="col-sm-2" align="right">
                        <label class="control-label">Amount:</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= @transaction.amount %></p>
                            <p class="help-block"></p>
                        </div>

                        <div class="col-sm-2" align="right">
                        <label class="control-label">Braintree Status</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= Braintree::Transaction.find(@transaction.braintreeid).status %></p>
                            <p class="help-block"></p>
                        </div>




                        <h3>Contact</h3>
                        <div class="col-sm-2" align="right">
                        <label class="control-label">Firstname:</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= @billingcustomer.firstname %></p>
                            <p class="help-block"></p>
                        </div>

                        <div class="col-sm-2" align="right">
                        <label class="control-label">Lastname:</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= @billingcustomer.lastname %></p>
                            <p class="help-block"></p>
                        </div>

                        <div class="col-sm-2" align="right">
                        <label class="control-label">Email:</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= @billingcustomer.email %></p>
                            <p class="help-block"></p>
                        </div>

                        <div class="col-sm-2" align="right">
                        <label class="control-label">Telephone:</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= @billingcustomer.telephone %></p>
                            <p class="help-block"></p>
                        </div>


                        <h3>Address</h3>
                        <div class="col-sm-2" align="right">
                        <label class="control-label">Street:</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= @billingaddress.address %></p>
                            <p class="help-block"></p>
                        </div>

                        <div class="col-sm-2" align="right">
                        <label class="control-label">Country:</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= Country.find( @billingaddress.country_id ).name %></p>
                            <p class="help-block"></p>
                        </div>

                        <div class="col-sm-2" align="right">
                        <label class="control-label">City:</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= @billingaddress.city %></p>
                            <p class="help-block"></p>
                        </div>

                        <div class="col-sm-2" align="right">
                        <label class="control-label">State:</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= @billingaddress.state %></p>
                            <p class="help-block"></p>
                        </div>

                        <div class="col-sm-2" align="right">
                        <label class="control-label">Zip:</label>
                        </div>
                        <div class="col-sm-10">
                            <p  class="form-control"><%= @billingaddress.zip %></p>
                            <p class="help-block"></p>
                        </div>



                    </div>

                  </div>


              </div>
            </div>

            </form>
          </div>
        </div>
    </div>

app/views/sale/_listallsales.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Sales</h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Sales</h3>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="tab-pane" id="tab-discount">
          <div class="table-responsive">
            <table id="discount" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <td class="text-left">ID</td>
                  <td class="text-left">Created at</td>
                  <td class="text-left">Braintree ID</td>
                  <td class="text-left">Amount</td>
                  <td class="text-left">Status</td>
                  <td class="text-left">Action</td>

                </tr>
              </thead>
              <tbody>
                  <%   @orderstransaction.each do |t| %>
                <tr>

                      <td><%= t.order_id %></td>
                      <td><%= t.created_at %></td>
                      <td><%= t.braintreeid %></td>
                      <td><%= t.amount %></td>
                      <td><%= OrderStatus.find( Order.find( t.order_id ).order_status_id ).name %></td>

                  <td>
                   <%= link_to '', details_sale_index_path( :id => t.id ), :class=>"btn btn-default fa fa-search", remote: true %>

                  <!-- <a href="/category/status/<%= t.id %>" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></td>
                  <a href="/admin/index" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></div></td> -->
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  </div>

app/views/sale/_listcanceledsales.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Canceled sales</h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Sales</h3>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="tab-pane" id="tab-discount">
          <div class="table-responsive">
            <table id="discount" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <td class="text-left">ID</td>
                  <td class="text-left">Created at</td>
                  <td class="text-left">Braintree ID</td>
                  <td class="text-left">Amount</td>
                  <td class="text-left">Status</td>
                  <td class="text-left">Action</td>

                </tr>
              </thead>
              <tbody>
                  <%   @orderstransaction.each do |t| %>
                <tr>

                      <td><%= t.order_id %></td>
                      <td><%= time_ago_in_words( t.created_at ) + " ago" %></td>
                      <td><%= t.braintreeid %></td>
                      <td><%= t.amount %></td>
                      <td><%= OrderStatus.find( Order.find( t.order_id ).order_status_id ).name %></td>

                  <td>
                   <%= link_to '', details_sale_index_path( :id => t.id ), :class=>"btn btn-default fa fa-search", remote: true %>

                  <!-- <a href="/category/status/<%= t.id %>" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></td>
                  <a href="/admin/index" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></div></td> -->
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  </div>

app/views/sale/_listcompletedsales.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Completed sales</h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Sales</h3>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="tab-pane" id="tab-discount">
          <div class="table-responsive">
            <table id="discount" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <td class="text-left">ID</td>
                  <td class="text-left">Created at</td>
                  <td class="text-left">Braintree ID</td>
                  <td class="text-left">Amount</td>
                  <td class="text-left">Status</td>
                  <td class="text-left">Action</td>

                </tr>
              </thead>
              <tbody>
                  <%   @orderstransaction.each do |t| %>
                <tr>

                      <td><%= t.order_id %></td>
                      <td><%= time_ago_in_words( t.created_at ) + " ago" %></td>
                      <td><%= t.braintreeid %></td>
                      <td><%= t.amount %></td>
                      <td><%= OrderStatus.find( Order.find( t.order_id ).order_status_id ).name %></td>

                  <td>
                   <%= link_to '', details_sale_index_path( :id => t.id ), :class=>"btn btn-default fa fa-search", remote: true %>

                  <!-- <a href="/category/status/<%= t.id %>" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></td>
                  <a href="/admin/index" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></div></td> -->
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  </div>

app/views/sale/_listprocessingsales.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Processing sales</h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Sales</h3>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="tab-pane" id="tab-discount">
          <div class="table-responsive">
            <table id="discount" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <td class="text-left">ID</td>
                  <td class="text-left">Created at</td>
                  <td class="text-left">Braintree ID</td>
                  <td class="text-left">Amount</td>
                  <td class="text-left">Status</td>
                  <td class="text-left">Action</td>

                </tr>
              </thead>
              <tbody>
                  <%   @orderstransaction.each do |t| %>
                <tr>

                      <td><%= t.order_id %></td>
                      <td><%= time_ago_in_words( t.created_at ) + " ago" %></td>
                      <td><%= t.braintreeid %></td>
                      <td><%= t.amount %></td>
                      <td><%= OrderStatus.find( Order.find( t.order_id ).order_status_id ).name %></td>

                  <td>
                   <%= link_to '', details_sale_index_path( :id => t.id ), :class=>"btn btn-default fa fa-search", remote: true %>

                  <!-- <a href="/category/status/<%= t.id %>" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></td>
                  <a href="/admin/index" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></div></td> -->
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  </div>

app/views/sale/_listsales.html.erb
 <div id="page-wrapper" style="background-color: #FFFFFF; margin-top: 15px">

<div class="container-fluid">

    <div class="pull-right">
      <a href="/admin/index" data-toggle="tooltip" title="Cancel" class="btn btn-default"><i class="fa fa-reply"></i></a></div>
      <h1>Latest sales</h1>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i>Sales</h3>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="tab-pane" id="tab-discount">
          <div class="table-responsive">
            <table id="discount" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <td class="text-left">ID</td>
                  <td class="text-left">Created at</td>
                  <td class="text-left">Braintree ID</td>
                  <td class="text-left">Amount</td>
                  <td class="text-left">Status</td>
                  <td class="text-left">Action</td>

                </tr>
              </thead>
              <tbody>
                  <%   @orderstransaction.each do |t| %>
                <tr>

                      <td><%= t.order_id %></td>
                      <td><%= time_ago_in_words( t.created_at ) + " ago" %></td>
                      <td><%= t.braintreeid %></td>
                      <td><%= t.amount %></td>
                      <td><%= OrderStatus.find( Order.find( t.order_id ).order_status_id ).name %></td>

                  <td>
                   <%= link_to '', details_sale_index_path( :id => t.order_id ), :class=>"btn btn-default fa fa-search", remote: true %>

                  <!-- <a href="/category/status/<%= t.id %>" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></td>
                  <a href="/admin/index" data-toggle="tooltip" title="Active / Disable" class="btn btn-default"><i class="fa fa-eye"></i></a></div></td> -->
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  </div>

app/views/sale/details.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( "details" ) ) %>" );

app/views/sale/listallsales.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( "listallsales" ) ) %>" );

app/views/sale/listcanceledsales.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( "listcanceledsales" ) ) %>" );

app/views/sale/listcompletedsales.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( "listcompletedsales" ) ) %>" );

app/views/sale/listprocessingsales.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( "listprocessingsales" ) ) %>" );

app/views/sale/listsales.js.erb
$( "#indexcambio" ).html( "<%= escape_javascript( render( "listsales" ) ) %>" );